### ISSUE TITLE
Unexpected token in combobox.js

### ISSUE THREAD

**Issue by oriharel** [rackt/react-autocomplete#27]
I've npm install react-autocomplete. but when I gulp, I get this:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Parsing file /Users/oriharel/oriApp/sixdegrees/node_modules/react-autocomplete/lib/combobox.js: Unexpected token (358:6)
    at Deps.parseDeps (/Users/oriharel/oriApp/sixdegrees/node_modules/browserify/node_modules/module-deps/index.js:418:28)
    at fromSource (/Users/oriharel/oriApp/sixdegrees/node_modules/browserify/node_modules/module-deps/index.js:361:48)
    at /Users/oriharel/oriApp/sixdegrees/node_modules/browserify/node_modules/module-deps/index.js:356:17
    at ConcatStream.<anonymous> (/Users/oriharel/oriApp/sixdegrees/node_modules/browserify/node_modules/concat-stream/index.js:32:43)
    at ConcatStream.EventEmitter.emit (events.js:117:20)
    at finishMaybe (/Users/oriharel/oriApp/sixdegrees/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/Users/oriharel/oriApp/sixdegrees/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/Users/oriharel/oriApp/sixdegrees/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DuplexWrapper.onend (/Users/oriharel/oriApp/sixdegrees/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at DuplexWrapper.g (events.js:180:16)
    at DuplexWrapper.EventEmitter.emit (events.js:117:20)
    at /Users/oriharel/oriApp/sixdegrees/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:934:16
    at process._tickCallback (node.js:415:13)

It looks like I'm expected to react transform the combobox jsx to js. but it's in the node_modules.
So, is this the case and if so, how to add the task to do it?

**Comment by KaeruCT** [comment]
:+1: having the same issue here

**Comment by Divinare** [comment]
Same issue here

**Comment by oriharel** [comment]
Don't waste your time guys. This is a dead project. get react-select instead.

**Comment by Divinare** [comment]
Thanks! That react-select looks good.
